import os
import sys
import json
import importlib.resources

from .maze import Maze, Player
from .bee import BeeMazeType
from .pvz import ZombieMazeType
from .farmer import FarmerMazeType
from .harvester import HarvesterMazeType
from .birds import BirdsMazeType
from .collector import CollectorMazeType

# Get the directory of the Python file being run
_script_path = os.path.dirname(os.path.realpath(sys.argv[0]))


def _find_level_file(filename):
    """
    Locates a level json file, preferring a local/dev copy (e.g. one just generated by the
    importer and not yet copied into maze/levels) over the one packaged with the maze module.
    Returns an open()-able path/traversable, or None if not found.
    """
    if not filename.endswith(".json"):
        filename = f"{filename}.json"

    for candidate in (
        filename,
        os.path.join(_script_path, filename),
        os.path.join(_script_path, "levels", filename),
    ):
        if os.path.exists(candidate):
            return candidate

    packaged = importlib.resources.files("maze.levels").joinpath(os.path.basename(filename))
    if packaged.is_file():
        return packaged

    return None


class Puzzle:
    mazeTypes = {
        "bee": BeeMazeType(),
        "pvz": ZombieMazeType(),
        "farmer": FarmerMazeType(),
        "harvester": HarvesterMazeType(),
        "birds": BirdsMazeType(),
        "collector": CollectorMazeType()
    }

    @staticmethod
    def from_file(filename):
        resolved = _find_level_file(filename)
        if resolved is None:
            raise TypeError("Unable to find file for level " + filename)

        # `resolved` is either a plain path (str) or an importlib.resources Traversable
        opener = resolved.open if hasattr(resolved, "open") else lambda: open(resolved)
        with opener() as fp:
            level_json = json.load(fp)

            game_id = level_json.get("game_id")
            if game_id and int(game_id) == 25:
                levelProps = level_json['properties']

                mazeType = Puzzle.mazeTypes[levelProps["skin"]]

                return Maze(level_json, mazeType)
            else:
                print(f"Unknown game_id: {game_id}")

    @staticmethod
    def done():
        Maze.instance.done()
